---
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/biodiff"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/container-attack-navigator"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/elastic-lab"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/flightsim"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

   - package-ecosystem: "docker"
    directory: "/fq"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/hfinger"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/marimo"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/misp-guard"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/nDPI"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/open-webui"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/snort2suricata"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "docker"
    directory: "/webdav"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/zeek"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
